export const COLLECTIONS = {
  users: "users",
  expenses: "expenses",
  expense_participants: "expense_participants",
  expenseParticipants: "expense_participants",
  groups: "groups",
  group_members: "group_members",
  settlements: "settlements",
  friendships: "friendships",
  invitations: "invitations",
  notifications: "notifications",
  notes: "notes",
  activities: "activity_logs",
  feedback: "feature_feedback",
  payment_reminders: "payment_reminders",
  recurring_templates: "recurring_templates",
  recurringExpenseTemplates: "recurring_templates",
  userNudgeStates: "user_nudge_states",
  recurring_runs: "recurring_runs",
  recurringExpenseRuns: "recurring_runs",
  user_budgets: "user_budgets",
  expenseComments: "expense_comments",
} as const;
